[package]
name = "guessing_game"
version = "0.1.0"
authors = ["kirinnee <kirinnee97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.5.0"
